name: Keep Bot Awake

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  ping-render-healthz:
    runs-on: ubuntu-latest
    steps:
      - name: Send /healthz ping
        # Simple GET request to the new /healthz endpoint.
        # No secret token or complex payload needed.
        # -f (--fail): Make curl exit with error if HTTP status >= 400
        # || true: Prevent workflow failure on transient curl errors
        run: |
          curl -fsS https://asiatekbot.onrender.com/healthz || true
