name: Keep Bot Awake

on:
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET to Render keep-alive endpoint
        run: |
          run: curl -X POST -H "Content-Type: application/json" -d '{"message":"ping"}' https://api.telegram.org/bot<YOUR_BOT_TOKEN>/sendMessage
