name: Keep Bot Awake
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Hit /keep-alive
        run: |
          curl -sSf https://asiatekbot.onrender.com/keep-alive || true
