name: Keep Bot Awake

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:   # ← allows manual runs

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET to Render webhook
        run: |
          curl --max-time 10 https://asiatekbot.onrender.com/webhook || true
