name: Keep Bot Awake

on:
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET to Render keep-alive endpoint
        run: |
          curl --max-time 10 https://asiatekbot.onrender.com/keep-alive || true
