name: Keep Bot Awake

# runs every 15 minutes
on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET to Render webhook
        run: |
          curl --max-time 10 https://asiatekbot.onrender.com/webhook || true
          
